CREATE TABLE IF NOT EXISTS CENTER
(
   `ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
   `STUDENT_NUMBER` VARCHAR (300) NOT NULL,
   `STUDENT_NAME` VARCHAR (300) NOT NULL,
   `EXAM_CENTER_NAME` VARCHAR (300) NOT NULL,
   `COLLEGE_NAME` VARCHAR (20) NOT NULL,
   `DATE_TIME` DATETIME NOT NULL,
   PRIMARY KEY (ID)
);