server:
    port: 9999
spring:
    application:
        name: gateway
zuul:
    routes:
        Product-service1:
            path: //**
            url: http://localhost:8999/
            stripPrefix: false
        Product-service2:
            path: //**
            url: http://localhost:8777/
            stripPrefix: false
    sensitiveHeaders: Cookie,Set-Cookie
    host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 1000000